===================================
How to expose custom smart pointer?
===================================

------------
Introduction
------------

.. include:: ./definition.irest

Files
-----

.. toctree::

  smart_ptr.h.rest
  classes.hpp.rest
  bindings.cpp.rest
  sconstruct.rest
  test.py.rest

All files contain comments, which describe what and why was done.

--------
Download
--------

`smart_ptrs.zip`_

.. _`smart_ptrs.zip` : ./smart_ptrs.zip


.. _`Py++` : ./../pyplusplus.html
.. _`pygccxml` : http://www.language-binding.net/pygccxml/pygccxml.html
.. _`SourceForge`: http://sourceforge.net/index.php

