========
Examples
========

.. contents:: Table of contents

-------------------
Graphical interface
-------------------

`pyplusplus`_ has nice, small and simple `graphical interface`_. Please, read 
`tutorials`_ for more information.

.. _`graphical interface` : ./../tutorials/pyplusplus_demo.png
.. _`tutorials` : ./../tutorials/tutorials.html

---------
pyeasybmp
---------

`EasyBMP`_ is a small cross-platform library that provide you functionality
needed to work with Windows bitmap (BMP) image files. I took me only few minutes
to create Python bindings for the library. Read more `here`__.

..  __ : ./easybmp/easybmp.html

---------------
boost libraries
---------------

Boost provides free peer-reviewed portable C++ source libraries. 

Using `pyplusplus`_ I created Python bindings for few libraries:

  * `boost.date_time`_
  * `boost.crc`_
  * `boost.rational`_
  * `boost.random`_

This is not "just another example". I went father and created new package: 
`pyboost`_. This is fully working Python package, with almost all unit test from
the libraries ported to Python. For more information please read `pyboost`_ 
package documentation.

.. _`pyboost` : ./boost/boost.html
  
.. _`boost.date_time` : http://boost.org/doc/html/date_time.html
.. _`boost.crc` : http://boost.org/libs/crc/index.html
.. _`boost.rational` : http://boost.org/libs/rational/index.html
.. _`boost.random` : http://boost.org/libs/random/index.html

.. _`GUI`: ./../tutorials/pyplusplus_demo.png
.. _`boost.python`: http://www.boost.org/libs/python/doc/index.html
.. _`pyplusplus` : ./../pyplusplus.html
.. _`EasyBMP`: http://easybmp.sourceforge.net/

..
   Local Variables:
   mode: indented-text
   indent-tabs-mode: nil
   sentence-end-double-space: t
   fill-column: 70
   End:
