# This file has been generated by Py++.

import ctypes

import ctypes_utils

libfunction_ptr_as_variable_lib = ctypes.CDLL( r"/home/roman/language-binding/sources/pyplusplus_dev/unittests/data/ctypes/function_ptr_as_variable/binaries/libfunction_ptr_as_variable.so" )

libfunction_ptr_as_variable_lib.undecorated_names = {#mapping between decorated and undecorated names
    "extern int execute_callback(info * info, int arg1) [free function]" : "_Z16execute_callbackP4infoi", 
    "_Z16execute_callbackP4infoi" : "extern int execute_callback(info * info, int arg1) [free function]", 
}

class info(ctypes.Structure):
    """class info"""

info._fields_ = [ #class info
    ("do_smth_fun", ctypes.CFUNCTYPE( ctypes.c_int, ctypes.c_int )),
]

do_smth_fun_t = ctypes.CFUNCTYPE( ctypes.c_int, ctypes.c_int )

execute_callback_type = ctypes.CFUNCTYPE( ctypes.c_int, ctypes.POINTER( info ), ctypes.c_int  )
execute_callback = execute_callback_type( ( libfunction_ptr_as_variable_lib.undecorated_names["extern int execute_callback(info * info, int arg1) [free function]"], libfunction_ptr_as_variable_lib ) )
