Boost.Python has a limitation: it does not allow to create classes, which derives
from the classes defined in Python. It is impossible to solve the general use case,
without changing the library, but it is pretty simple to create solution for 
"exception" classes.
