==============================
Boost.Python - lessons learned
==============================

--------
Preamble
--------

Software development is an interactive process. During `Py++` development
I see many interesting problems and even more interesting solutions.

On this page you will find my collection of the solutions to some of the problems.

.. toctree::

   easy_extending_guide <easy_extending_guide/easy_extending_guide.rest>

   custom smart pointer class <smart_ptrs/smart_ptrs.rest>

   `boost::shared_ptr< const T>` <shared_ptr/shared_ptr.rest>

   automatic conversion <automatic_conversion/automatic_conversion.rest>

   exceptions <exceptions/exceptions.rest>

