#! /usr/bin/python
# Copyright 2004 Roman Yakovenko.
# Distributed under the Boost Software License, Version 1.0. (See
# accompanying file LICENSE_1_0.txt or copy at
# http://www.boost.org/LICENSE_1_0.txt)

import os
import sys
import settings

def get_ccflags():
    if sys.platform == 'win32':
        return settings.scons.ccflags \
               + map( lambda ds: '/D%s' % ds, settings.defined_symbols )
    else:
        return map( lambda ds: '-D' + ds, settings.defined_symbols )

def get_py_date_time_files():
    source_files = filter( lambda s: s.endswith( '.cpp' ), os.listdir(settings.generated_files_dir) )
    return map( lambda fname: os.path.join( settings.generated_files_dir, fname ), source_files )

def get_libs():
    if sys.platform == 'win32':
        return ['boost_python' ]
    else:
        return ['boost_python', 'libboost_date_time-gcc-1_34']

def get_target():
    return os.path.join( settings.generated_files_dir
                         , settings.module_name + settings.scons.suffix )

SharedLibrary( target=get_target()
               , source=get_py_date_time_files()
               , LIBS=get_libs()
               , LIBPATH=[ settings.boost.libs, settings.python.libs ]
               , CPPPATH=[ settings.boost.include
                           , settings.working_dir
                           , settings.python.include
                           , settings.generated_files_dir ]
               , CCFLAGS=get_ccflags()
               , SHLIBPREFIX=''
               , SHLIBSUFFIX=settings.scons.suffix )
