// This file has been generated by pyplusplus.

// std directories: []
// user defined directories: []

#include "boost/python.hpp"

#include "d:/pygccxml_sources/source/pyplusplus/unittests/data/call_policies_to_be_exported.hpp"

namespace bp = boost::python;

BOOST_PYTHON_MODULE(pyplusplus){
    bp::class_< call_policies::dummy >( "dummy" )    
        .def( "id"
                , &call_policies::dummy::id
                , bp::default_call_policies() );

    bp::def( "compare"
            , &call_policies::void_ptr::compare
            , ( bp::arg("ptr") )
            , bp::default_call_policies() );

    bp::def( "my_address"
            , &call_policies::void_ptr::my_address
            , bp::return_value_policy< bp::return_opaque_pointer, bp::default_call_policies >() );

    bp::def( "copy_const_reference"
            , &call_policies::return_value_policy::copy_const_reference
            , ( bp::arg("x") )
            , bp::return_value_policy< bp::copy_const_reference, bp::default_call_policies >() );

    bp::def( "return_self"
            , &call_policies::return_self::return_self
            , ( bp::arg("x"), bp::arg("y") )
            , bp::return_value_policy< bp::copy_const_reference, bp::default_call_policies >() );

    bp::def( "return_second_arg"
            , &call_policies::return_arg::return_second_arg
            , ( bp::arg("arg0"), bp::arg("x"), bp::arg("arg2") )
            , bp::default_call_policies() );
}
