// This file has been generated by pyplusplus.

// Copyright 2004 Roman Yakovenko.
// Distributed under the Boost Software License, Version 1.0. (See
// accompanying file LICENSE_1_0.txt or copy at
// http://www.boost.org/LICENSE_1_0.txt)

#include "boost/python.hpp"
#ifdef _MSC_VER
    #pragma hdrstop
#endif //_MSC_VER

#include "unittests/data/call_policies_to_be_exported.hpp"

namespace bp = boost::python;

BOOST_PYTHON_MODULE(call_policies){
    bp::class_< call_policies::dummy >( "dummy" )    
        .def( "id"
                , &call_policies::dummy::id
                , bp::default_call_policies() );

    bp::class_< call_policies::return_value_policy::container >( "container" )    
        .def( "__getitem__"
                , &call_policies::return_value_policy::container::operator[]
                , ( bp::arg("i") )
                , bp::default_call_policies() );

    bp::def( "compare"
            , &call_policies::void_ptr::compare
            , ( bp::arg("ptr") )
            , bp::default_call_policies() );

    bp::def( "my_address"
            , &call_policies::void_ptr::my_address
            , bp::return_value_policy< bp::return_opaque_pointer, bp::default_call_policies >() );

    bp::def( "copy_const_reference"
            , &call_policies::return_value_policy::copy_const_reference
            , ( bp::arg("x") )
            , bp::return_value_policy< bp::copy_const_reference, bp::default_call_policies >() );

    bp::def( "return_self"
            , &call_policies::return_self::return_self
            , ( bp::arg("x"), bp::arg("y") )
            , bp::return_self< bp::default_call_policies >() );

    bp::def( "return_second_arg"
            , &call_policies::return_arg::return_second_arg
            , ( bp::arg("arg0"), bp::arg("x"), bp::arg("arg2") )
            , bp::return_arg< 2, bp::default_call_policies >() );
}
