// This file has been generated by pyplusplus.

// Copyright 2004 Roman Yakovenko.
// Distributed under the Boost Software License, Version 1.0. (See
// accompanying file LICENSE_1_0.txt or copy at
// http://www.boost.org/LICENSE_1_0.txt)

#include "boost/python.hpp"
#ifdef _MSC_VER
    #pragma hdrstop
#endif //_MSC_VER

#include "unittests/data/class_order_to_be_exported.hpp"

namespace bp = boost::python;

BOOST_PYTHON_MODULE(class_order){
    bp::class_< class_order::container >( "container", bp::init< bp::optional< class_order::item const & > >() )    
        .def_readonly( "my_item", &class_order::container::my_item );

    bp::implicitly_convertible< class_order::item const &, class_order::container >();

    bp::class_< class_order::item >( "item", bp::init< int, int >()[bp::default_call_policies()] )    
        .def_readwrite( "m_value", &class_order::item::m_value );
}
