// This file has been generated by pyplusplus.

// Copyright 2004 Roman Yakovenko.
// Distributed under the Boost Software License, Version 1.0. (See
// accompanying file LICENSE_1_0.txt or copy at
// http://www.boost.org/LICENSE_1_0.txt)

#include "boost/python.hpp"
#ifdef _MSC_VER
    #pragma hdrstop
#endif //_MSC_VER

#include "unittests/data/free_functions_to_be_exported.hpp"

namespace bp = boost::python;

BOOST_PYTHON_MODULE(free_functions){
    bp::def( "plus"
            , &free_functions::plus
            , ( bp::arg("a"), bp::arg("b")=21 )
            , bp::default_call_policies() );

    bp::def( "ONE"
            , &free_functions::one
            , bp::default_call_policies() );
}
