// This file has been generated by pyplusplus.

// Copyright 2004 Roman Yakovenko.
// Distributed under the Boost Software License, Version 1.0. (See
// accompanying file LICENSE_1_0.txt or copy at
// http://www.boost.org/LICENSE_1_0.txt)

#include "boost/python.hpp"
#ifdef _MSC_VER
    #pragma hdrstop
#endif //_MSC_VER

#include "unittests/data/optional_bug_to_be_exported.hpp"

namespace bp = boost::python;

BOOST_PYTHON_MODULE(optional_bug){
    bp::class_< optional_bug::data >( "data" )    
        .def( bp::init< >()[bp::default_call_policies()] )    
        .def( bp::init< int, int, bp::optional< int, int > >(( bp::arg("a"), bp::arg("b"), bp::arg("c")=0, bp::arg("d")=0 ))[bp::default_call_policies()] );
}
