// This file has been generated by pyplusplus.

// Copyright 2004 Roman Yakovenko.
// Distributed under the Boost Software License, Version 1.0. (See
// accompanying file LICENSE_1_0.txt or copy at
// http://www.boost.org/LICENSE_1_0.txt)

#include "boost/python.hpp"
#ifdef _MSC_VER
    #pragma hdrstop
#endif //_MSC_VER

#include "unittests/data/optional_to_be_exported.hpp"

namespace bp = boost::python;

BOOST_PYTHON_MODULE(optional){
    bp::class_< optional_args::data2 >( "data2", bp::init< int, bp::optional< int > >(( bp::arg("i"), bp::arg("j") ))[bp::default_call_policies()] )    
        .def_readwrite( "m_i", &optional_args::data2::m_i )    
        .def_readwrite( "m_j", &optional_args::data2::m_j );

    bp::class_< optional_args::data >( "data", bp::init< bp::optional< int, int > >(( bp::arg("i"), bp::arg("j") ))[bp::default_call_policies()] )    
        .def_readwrite( "m_i", &optional_args::data::m_i )    
        .def_readwrite( "m_j", &optional_args::data::m_j );
}
