// This file has been generated by pyplusplus.

// Copyright 2004 Roman Yakovenko.
// Distributed under the Boost Software License, Version 1.0. (See
// accompanying file LICENSE_1_0.txt or copy at
// http://www.boost.org/LICENSE_1_0.txt)

#include "boost/python.hpp"
#ifdef _MSC_VER
    #pragma hdrstop
#endif //_MSC_VER

#include "unittests/data/pointer_as_arg_to_be_exported.hpp"

namespace bp = boost::python;

BOOST_PYTHON_MODULE(pointer_as_arg){
    bp::class_< pointer_as_arg::data >( "data" );

    bp::def( "test_for_null"
            , &pointer_as_arg::test_for_null
            , ( bp::arg("d")=bp::object() )
            , bp::default_call_policies() );
}
