// This file has been generated by pyplusplus.

// Copyright 2004 Roman Yakovenko.
// Distributed under the Boost Software License, Version 1.0. (See
// accompanying file LICENSE_1_0.txt or copy at
// http://www.boost.org/LICENSE_1_0.txt)

#include "boost/python.hpp"
#ifdef _MSC_VER
    #pragma hdrstop
#endif //_MSC_VER

#include "unittests/data/private_assign_to_be_exported.hpp"

namespace bp = boost::python;

BOOST_PYTHON_MODULE(private_assign){
    bp::class_< private_assign::container_t >( "container_t" )    
        .def( bp::init< >()[bp::default_call_policies()] )    
        .def_readonly( "m_item", &private_assign::container_t::m_item );

    bp::class_< private_assign::item_t >( "item_t" )    
        .def( bp::init< >()[bp::default_call_policies()] )    
        .def_readwrite( "m_value", &private_assign::item_t::m_value );
}
