// This file has been generated by pyplusplus.

// Copyright 2004 Roman Yakovenko.
// Distributed under the Boost Software License, Version 1.0. (See
// accompanying file LICENSE_1_0.txt or copy at
// http://www.boost.org/LICENSE_1_0.txt)

#include "boost/python.hpp"
#ifdef _MSC_VER
    #pragma hdrstop
#endif //_MSC_VER

#include "unittests/data/statics_to_be_exported.hpp"

namespace bp = boost::python;

BOOST_PYTHON_MODULE(statics){
    bp::class_< statics::data >( "data" )    
        .def( bp::init< >()[bp::default_call_policies()] )    
        .def( "instances_count"
                , (int (*)(  ))(&statics::data::instances_count)
                , bp::default_call_policies() )    
        .staticmethod( "instances_count" );

    bp::def( "data_instances_count"
            , &statics::data_instances_count
            , bp::default_call_policies() );
}
