#! /usr/bin/python
# Copyright 2004 Roman Yakovenko.
# Distributed under the Boost Software License, Version 1.0. (See
# accompanying file LICENSE_1_0.txt or copy at
# http://www.boost.org/LICENSE_1_0.txt)

import sys
sys.path.append( './../..' )
import environment

env = Environment(
      LIBS=['boost_python']
    , LIBPATH=[ environment.boost.libs, environment.python.libs ]
    , CPPPATH=[ environment.boost.include, environment.python.include ]
    , SHLIBPREFIX=''
    , SHLIBSUFFIX=environment.scons.suffix  
)

if sys.platform == 'win32':
    env.Replace( no_import_lib=1 )
else:
    env.Append( CCFLAGS=' -ggdb3 -DNDEBUG -O3' )

Export( 'env' )
env.SConscript( ['dev/date_time/sconscript'] )
env.SConscript( ['dev/crc/sconscript'] )
env.SConscript( ['dev/boost_random/sconscript'] )
env.SConscript( ['dev/rational/sconscript'] )