=====
Links
=====

.. contents:: Table of contents

----
Wiki
----

Thanks to Allen Bierbaum `Py++`_ now has `wiki`_. We use it primary to
discuss new features, which will be introduced in future versions.

.. _`wiki` : https://realityforge.vrsource.org/view/PyppApi/WebHome

-------
Reading
-------

* `Building Hybrid Systems with Boost.Python`_

  .. _`Building Hybrid Systems with Boost.Python` : http://www.boost-consulting.com/writing/bpl.html

* `A rationale for semantically enhanced library languages`_

  .. _`A rationale for semantically enhanced library languages` : http://www.research.att.com/~bs/SELLrationale.pdf

  ".. A Semantically Enhanced Library Language (a SEL language or a SELL) is a 
  dialect created by supersetting a language using a library and then subsetting
  the result using a tool that `understands` the syntax and semantics of both 
  the underlying language and the library. ..."
  
  `Py++`_ + Boost.Python is a SELL!
  

* `Aspect oriented programming`_

  .. _`Aspect oriented programming` : http://en.wikipedia.org/wiki/Aspect-oriented_programming

  `Py++`_ borrowed few ideas from this programming paradigm.

--------------
Help resources
--------------

* http://www.google.com :-)

* http://boost.org/libs/python/doc/index.html - tutorials, FAQs, reference 
  manuals
  
* `Boost.Python wiki`_

  .. _`Boost.Python wiki` : http://wiki.python.org/moin/boost%2epython?action=show&redirect=boost+2epython

* http://boost.cvs.sourceforge.net/boost/boost/libs/python/test/ - `Boost.Python`_ 
  unit tests. They could be very, very helpful.

* http://svn.sourceforge.net/viewvc/pygccxml/pyplusplus_dev/unittests/ - `Py++`_ 
  unit tests. They could be even more helpful!
  
-------------
Mailing lists
-------------

* `C++-sig`_ - development of Python/C++ bindings

  .. _`C++-sig` : http://mail.python.org/mailman/listinfo/c++-sig/

* `Py++ mailing list`_

  .. _`Py++ mailing list` : http://sourceforge.net/mail/?group_id=118209

.. _`Boost.Python`: http://www.boost.org/libs/python/doc/index.html
.. _`Py++` : ./pyplusplus.html

..
   Local Variables:
   mode: indented-text
   indent-tabs-mode: nil
   sentence-end-double-space: t
   fill-column: 70
   End:

