====
TODO
====

.. contents:: Table of contents

-----------
Description
-----------

This page is an official `Py++`_ "TODO" page.

For small features, the description of the feature and it's implementation will
be written here. Big features will get their own page.

---------------
Unnamed classes
---------------

There is no technical reason why unnamed classes/structs/unions are not exported

by `Py++`_:

::

  class Foo{
      union {
          struct {
              float r,g,b,a;
          };
          float val[4];
      };
  };


Implementation details
----------------------

As it seems to me, the only code that should be changed is
"pyplusplus/module_creator/creator.py" file. To be more specific: all code creators,
for declarations in unnamed classes, should be created under named class.

The coding itself should take something like 4 - 5 hours, including unit test.

---------------------
Call wrapper policies
---------------------

Not all functions could be exposed to Python as is. This `document`__ will
explain how `Py++`_ will help users to create wrappers around those functions.

.. __ : ./call_wrapper_policies.html


.. _`Py++` : ./../pyplusplus.html
.. _`Boost.Python`: http://www.boost.org/libs/python/doc/index.html
.. _`Python`: http://www.python.org
.. _`GCC-XML`: http://www.gccxml.org

..
   Local Variables:
   mode: indented-text
   indent-tabs-mode: nil
   sentence-end-double-space: t
   fill-column: 70
   End:

